server:
  port: 80

spring:
  application:
    name: crowd-zuul
  redis:
    host: 192.168.74.131
    port: 6379
  session:
    store-type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

zuul:
  ignored-services: "*"
  sensitive-headers: "*" # 在 Zuul 向其他微服务重定向时保持原本头信息（请求头、响应头）
  routes:
    crowd-portal:
      service-id: crowd-auth
      path: /** # 这里一定要使用两个“*”号，不然“/”路径后面的多层路径将无法访问
    crowd-project:
      service-id: crowd-project
      path: /project/**
    crowd-order:
      service-id: crowd-order
      path: /order/**
    crowd-pay:
      service-id: crowd-pay
      path: /pay/**
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 20000
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
feign:
  client:
    config:
      default:
        ConnectTimeOut: 10000
        ReadTimeOut: 10000