server:
  port: 5000
spring:
  application:
    name: crowd-project
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 192.168.74.131
  session:
    store-type: redis

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
aliyun:
  oss:
    access-key-id: LTAI5tEAsSKofc79XnrqFgVX
    access-key-secret: sUUrEa7Qs49UTlbyi3VtQn8jpM0ZNt
    bucket-domain: http://huangtianyi-oss.oss-cn-shenzhen.aliyuncs.com
    bucket-name: huangtianyi-oss
    end-point: Http://oss-cn-shenzhen.aliyuncs.com